apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-frontend
  labels:
    app: portfolio-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-frontend
  template:
    metadata:
      labels:
        app: portfolio-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/jterpstra1/prd-personal-portfolio-frontend:1.1.0
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr-pull-secret