apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-frontend
  labels:
    app: portfolio-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-frontend
  template:
    metadata:
      labels:
        app: portfolio-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/jterpstra1/personal-portfolio-frontend:0.0.11
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-backend
  labels:
    app: portfolio-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-backend
  template:
    metadata:
      labels:
        app: portfolio-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/jterpstra1/personal-portfolio-backend:0.0.5
          ports:
            - containerPort: 4000
          env:
            - name: ADMIN_HASH
              valueFrom:
                secretKeyRef:
                  name: personal-profile-admin-hash-secret
                  key: personal-profile-admin-hash
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: personal-profile-jwt-secret
                  key: personal-profile-jwt-secret
      imagePullSecrets:
        - name: ghcr-pull-secret