apiVersion: v1
kind: PersistentVolume
metadata:
  name: personal-profile-nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.1.230
    path: /srv/nfs/personal-profile

