apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-ui
spec:
  ingressClassName: nginx
  rules:
    - host: adguard-b.terpstra.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adguard-ui-b
                port:
                  number: 3000