apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect
  namespace: 1password
spec:
  replicas: 1
  selector:
    matchLabels: { app: onepassword-connect }
  template:
    metadata:
      labels: { app: onepassword-connect }
    spec:
      containers:
        - name: connect-api
          image: 1password/connect-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: OP_LOG_LEVEL
              value: info
          volumeMounts:
            - name: data
              mountPath: /home/opuser/.op/data
            - name: credentials
              mountPath: /home/opuser/.op/1password-credentials.json
              subPath: 1password-credentials.json
              readOnly: true
        - name: connect-sync
          image: 1password/connect-sync:latest
          env:
            - name: OP_LOG_LEVEL
              value: info
          volumeMounts:
            - name: data
              mountPath: /home/opuser/.op/data
            - name: credentials
              mountPath: /home/opuser/.op/1password-credentials.json
              subPath: 1password-credentials.json
              readOnly: true
      volumes:
        - name: data
          emptyDir: {}
        - name: credentials
          secret:
            secretName: onepassword-credentials
            items:
              - key: 1password-credentials.json
                path: 1password-credentials.json