apiVersion: v1
kind: Service
metadata:
  name: onepassword-connect
  namespace: 1password
spec:
  selector:
    app: onepassword-connect
  ports:
    - name: connect-api
      port: 8080
      targetPort: 8080