apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - pvc.yaml

nameSuffix: -a

patches:
  # Assign unique LoadBalancer IP and shared-ip annotation for DNS
  - target:
      kind: Service
      name: adguard-dns
    patch: |-
      - op: add
        path: /spec/loadBalancerIP
        value: 192.168.1.53
      - op: replace
        path: /metadata/annotations/metallb.universe.tf~1allow-shared-ip
        value: adguard-a
  # Assign shared-ip annotation and LoadBalancer IP for UI
  - target:
      kind: Service
      name: adguard-ui
    patch: |-
      - op: add
        path: /spec/loadBalancerIP
        value: 192.168.1.53
      - op: replace
        path: /metadata/annotations/metallb.universe.tf~1allow-shared-ip
        value: adguard-a
  - target:
      kind: PersistentVolume
      name: pv-adguard
    patch: |-
      - op: replace
        path: /metadata/name
        value: pv-adguard-a
      - op: replace
        path: /spec/nfs/path
        value: /srv/nfs/adguard-a