apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - pvc.yaml

nameSuffix: -a

patches:
  # Assign unique LoadBalancer IP for DNS
  - target:
      kind: Service
      name: adguard-dns
    patch: |-
      - op: add
        path: /spec/loadBalancerIP
        value: 192.168.1.53
  # Expose admin UI on same IP as DNS
  - target:
      kind: Service
      name: adguard-ui
    patch: |-
      - op: add
        path: /spec/loadBalancerIP
        value: 192.168.1.53
  - target:
      kind: PersistentVolume
      name: pv-adguard
    patch: |-
      - op: replace
        path: /metadata/name
        value: pv-adguard-a
      - op: replace
        path: /spec/nfs/path
        value: /srv/nfs/adguard-a