apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

nameSuffix: -a

patches:
  # Assign unique LoadBalancer IP for DNS
  - target:
      kind: Service
      name: adguard-dns
    patch: |-
      - op: add
        path: /spec/loadBalancerIP
        value: 192.168.1.53

  # Rename PVC so each instance gets its own storage
  - target:
      kind: PersistentVolumeClaim
      name: adguard-config
    patch: |-
      - op: replace
        path: /metadata/name
        value: adguard-config-a