apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: personal-profile-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeName: personal-profile-nfs-pv

