apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-cluster-store
spec:
  provider:
    onepassword:
      connectHost: "http://onepassword-connect.1password.svc.cluster.local:8080"
      vaults:
        ESO: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: prd-access-token
            namespace: external-secrets
            key: credential
