apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets-operator
  namespace: external-secrets
spec:
  selector:
    matchLabels:
      app: external-secrets-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: external-secrets-operator
    spec:
      serviceAccountName: external-secrets
      containers:
      - name: manager
        image: ghcr.io/external-secrets/external-secrets:v0.19.2
        args:
        - --install-crds=true