apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: onepassword
  namespace: external-secrets
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.1password:8080
      vaults:
        - name: my-vault   # the 1Password vault name
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-token
            key: token