apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-adguard
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.230
    path: /srv/nfs/adguard