apiVersion: v1
kind: Service
metadata:
  name: adguard-ui
  labels:
    app: adguard
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: adguard