apiVersion: v1
kind: Service
metadata:
  name: adguard-ui
  labels:
    app: adguard
  annotations:
    metallb.universe.tf/allow-shared-ip: TO_OVERLAY
spec:
  type: LoadBalancer
  loadBalancerIP: TO_OVERLAY
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: adguard