apiVersion: v1
kind: Service
metadata:
  name: adguard-dns
  labels:
    app: adguard
spec:
  type: LoadBalancer
  loadBalancerIP: TO_OVERLAY
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
  selector:
    app: adguard