#apiVersion: external-secrets.io/v1beta1
#kind: SecretStore
#metadata:
#  name: onepassword-store
#  namespace: external-secrets
#spec:
#  provider:
#    onepassword:
#      connectHost: "http://onepassword-connect:8080"
#      vaults:
#        ESO: "ESO"
#      auth:
#        secretRef:
#          connectTokenSecretRef:
#            name: prd-access-token
#            key: credential
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-cluster-store
spec:
  provider:
    onepassword:
      connectHost: "http://onepassword-connect:8080"
      vaults:
        ESO: "ESO"
      auth:
        secretRef:
          connectTokenSecretRef:
            name: prd-access-token
            namespace: managed-secrets   # 👈 required because the secret is namespaced
            key: credential
