apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: onepassword-store
  namespace: external-secrets
spec:
  provider:
    onepassword:
      connectHost: "http://onepassword-connect:8080"
      vaults:
        ESO: "ESO"
      auth:
        secretRef:
          connectTokenSecretRef:
            name: prd-access-token
            key: credential